### ISSUE TITLE
Build and test on CentOS 8

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/ssm#123]
Report to EGI: https://wiki.egi.eu/wiki/Next_middleware_release#Supported_products

Waiting on Cloud to add images integrated with Aquilon.

**Comment by harenber** [comment]
Dear all,

is there any news on porting to CentOS 8? It seems that ssm is one of the last parts that would be needed to be ported to run an ARC 6 CE on CentOS 8 in the EGI context. 

Cross reference: https://bugzilla.nordugrid.org/show_bug.cgi?id=3945

Thanks

  Torsten

**Comment by maikenp** [comment]
Adding a comment just to be alerted if some work is done on the issue.

**Comment by tofu-rocketry** [comment]
I'm chasing up the provision of CentOS 8 images for our test and build environment.

**Comment by tofu-rocketry** [comment]
Seems to work. Need to tidy up the spec file to specify Python version when building on CentOS 8.

**Comment by rptaylor** [comment]
Both CentOS7 and CentOS (Stream) 8 will be end of life in approximately 5 months.

As for (RH)EL8 it is getting a bit old (released almost 4 years ago), it would be good to have ssmsend available for EL9 as well.

**Comment by RedProkofiev** [comment]
> Both CentOS7 and CentOS (Stream) 8 will be end of life in approximately 5 months.
> 
> As for (RH)EL8 it is getting a bit old (released almost 4 years ago), it would be good to have ssmsend available for EL9 as well.

We're working on the basis of supporting Rocky 9 and Ubuntu 22 sooner rather than later: we're waiting on some test infrastructure since we're fairly sure our new build script should work well on both.  Will post updates.
