### ISSUE TITLE
Restart loop should watch for termination signals

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/ssm#133]
If SSM loses connection it waits 10 minutes to restart. However this loop isn't quitable. It should check for termination signals so that it can be stopped gracefully while it's waiting to restart.

**Comment by tofu-rocketry** [comment]
Hmm, this may or may not be an issue. What I saw might have been the init script not doing the right thing.

**Comment by tofu-rocketry** [comment]
This probably possibly be a loop with shorter sleeps: https://github.com/apel/ssm/blob/741b87bcf0a4238df118ee2d3d94c6ec0c67d05b/ssm/agents.py#L323

**Comment by tofu-rocketry** [comment]
Or use `threading.Event.wait`

**Comment by Will-Cross1** [comment]
After running the receiver and forcing it to reach the restart wait with no additions to the code, running `ps -ef | grep receiver` gives the number ID of the process that it is running.

Simply killing this number (e.g: `kill 3204`) causes the SystemExit exception to be ran inside the agents.py code which shuts down the ssm as is intended thereby not needing to alter any code for the desired outcome.


I also replaced the `time.sleep(10 * 60)` with a for loop sleeping the time every 1 second for 10 minuets (the same length of time) and it was also able to be killed in the same way

**Comment by tofu-rocketry** [comment]
Thanks for investigating this.
