### ISSUE TITLE
Deb packages should depend on python-stomp

### ISSUE THREAD

**Issue by enolfc** [apel/ssm#148]
While the dependency is fully removed #120, stomp should be a dependency of packages to avoid broken installations

**Comment by enolfc** [comment]
AFAIK, right now even if using AMS, stomp is a dependency in the code, so not installing stomp just makes ssmsend unusable. However as Stomp is not a dependency of the package you get this broken state of having ssm installed without its dependencies.

**Comment by tofu-rocketry** [comment]
It is currently a dependency though, so I'm a bit confused.

The RPM package is `stomppy`: https://github.com/apel/ssm/blob/3.1.1-1/apel-ssm.spec#L24
and the Python package is `stomp.py`: https://github.com/apel/ssm/blob/3.1.1-1/setup.py#L54

**Comment by enolfc** [comment]
I was looking at deb packages. Sorry I didn't specify that

**Comment by tofu-rocketry** [comment]
Ah, right! Thanks - that does seem like an oversight.
