### ISSUE TITLE
Check/warn if incorrect cert being used to encrypt messages

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/ssm#160]
From [GGUS](https://ggus.eu/index.php?mode=ticket_info&ticket_id=150955#update#16).

Would be useful if a client SSM could check if messages are being encrypted by a cert that's actually used by the central server that'll be eventually receiving the messages.

Might need to be able to fetch a DN from GOCDB.

**Comment by gregcorbett** [comment]
> Might need to be able to fetch a DN from GGUS.

Do you mean GOCDB?

**Comment by tofu-rocketry** [comment]
> Do you mean GOCDB?

Derp. Yes.

**Comment by tofu-rocketry** [comment]
To avoid having to fetch anything, we could just add a list of default host DNs that the cert should be for (i.e. the apel prod and pre-prod hosts) and have a config setting that can disable that check if really needed (e.g. regional servers) or override what host the DN can be for.
