### ISSUE TITLE
Accept data just by hostname rather than registered cert subject?

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/ssm#170]
From [GGUS](https://ggus.eu/index.php?mode=ticket_info&ticket_id=152235).

APEL accepts data only for certificate subject registered in GOCDB. This can be complicated for sites, because they have to remember to update GOCDB registration every time they get new certificate (and unfortunately certificate subject is not as stable as one would expect, because every few years with tender there is new CA provider and subject has different structure).

What's the value in validating whole certificate subject for accounting purposes? It would be easier to rely only on hostname in the subjectAlternativeName. This simple change could reduce problem like

https://ggus.eu/index.php?mode=ticket_info&ticket_id=151377

where it is not immediately clear what is causing troubles (actually this site had wrong subject registered in GOCDB for almost a year).

**Comment by tofu-rocketry** [comment]
Would be interested in thoughts from @jrha and @ineilson.

**Comment by ineilson** [comment]
I can't think of any value in matching the whole subject. I think the use of subject CN is, in fact, deprecated in favour of using the subject alt name field for host DNS names. RFC2818 -

>    If a subjectAltName extension of type dNSName is present, that MUST
>    be used as the identity. Otherwise, the (most specific) Common Name
>    field in the Subject field of the certificate MUST be used. Although
>    the use of the Common Name is existing practice, it is deprecated and
>    Certification Authorities are encouraged to use the dNSName instead.

Ref: https://groups.google.com/a/chromium.org/g/security-dev/c/IGT2fLJrAeo?pli=1 for example of debate over implementation here wrt the standard.

**Comment by jrha** [comment]
If you only want to verify that the host is what it claims to be, then verifying `subjectAltName`(s) should be all you need.

**Comment by jrha** [comment]
Is this an authentication problem, an authorisation problem, or both?

**Comment by gwarf** [comment]
Also commented on GGUS: one issue with this would be that it would prevent using robot certificate instead of hosts certificates, and we have been recently agreeing using robot certificates for sites that cannot access an IGTF CA, like for commercial providers joining FedCloud or for countries and institutes that don't have access to a national/NREN IGTF CA.

**Comment by tofu-rocketry** [comment]
Yeah, think it's best to leave it as is for now. Longer term we can look at using tokens the whole way through as an alternative with the Messaging team.
