### ISSUE TITLE
Logging doesn't capture filename on OSError

### ISSUE THREAD

**Issue by drebatto** [apel/ssm#172]
<strike>The `openssl` command is used in `/usr/lib/python2.7/site-packages/ssm/crypto.py`, but in a bare CentOS7 container the openssl package is not installed.</strike> [Fixed in 3.2.1] This lets `ssmsend` fail with an undescriptive error:
```
SSM failed to complete successfully.  See log file for details.
2021-07-16 13:28:17,357 - ssmsend - ERROR - Unexpected exception in SSM: [Errno 2] No such file or directory
2021-07-16 13:28:17,358 - ssmsend - ERROR - Exception type: <type 'exceptions.OSError'>
```

[Investigating this did highlight that `OSError` is a subclass of `EnvironmentError` and that has an additional `filename` attribute which isn't added to the standard `args` that the generic exception handling is set up to deal with. We could add some generic-ish handling for `EnvironmentError` that captures the filename. - AC]

**Comment by drebatto** [comment]
In general, I'd also suggest that you improve the error messages when `[Errno 2]` is found, by printing the failed file's name and path.

**Comment by tofu-rocketry** [comment]
What version of SSM? We added `openssl` as a dependency to 3.2.1 back in April (though admittedly it's only been added to UMD this month).

Was there any more log output after that point?

`OSError` is a subclass of `EnvironmentError` that has an additional `filename` attribute which isn't added to the standard `args` that the generic exception handling is set up to deal with. I guess we could add some generic-ish handling for `EnvironmentError`.

**Comment by drebatto** [comment]
Hi, the version was 3.2.0 from UMD. The subsequent lines in the log file were:
```
2021-07-27 16:43:54,409 - client - INFO - SSM has shut down.
2021-07-27 16:43:54,409 - client - INFO - ========================================
2021-07-27 16:43:54,410 - client - INFO - SSM stopped.
2021-07-27 16:43:54,410 - client - INFO - =====================
```

I have rebuilt the container yesterday, and now the ssm version is 3.2.1. I didn't try to remove the explicit installation of `openssl` from the Dockerfile, but I am reasonably convinced that it would have worked now.

Thanks,
David

**Comment by tofu-rocketry** [comment]
Thanks. That's good to hear. I've tweaked this issue to just track the lack of filename in the logging.

**Comment by tofu-rocketry** [comment]
With the changes made in #314, there should now be sufficient logging to track what file is causing the issue.

If you do come across this issue again, feel free to open a new one.
