### ISSUE TITLE
planning for python3?

### ISSUE THREAD

**Issue by adriansev** [apel/ssm#227]
Hi! Is there any planning for python3? (EL9/Alma9)
Thank you!

**Comment by tofu-rocketry** [comment]
We now have someone who has time to look at this, though they'll be starting with setting up environments, so if you already have changes ready to go, feel free to open a PR and we can work them in, but maybe don't do a bunch of new work just yet.

On the other hand, if you have suggested changes for the build processes specifically, then I would welcome those.

**Comment by tofu-rocketry** [comment]
I'm now working on the release branch for SSM 3.4.0 that has the fixes needed for this, so packages should be available this week.
