### ISSUE TITLE
Fix code scanning alert - Explicit return mixed with implicit (fall through) return

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/ssm#242]
Tracking issue for:
- [ ] https://github.com/apel/ssm/security/code-scanning/36

**Comment by tofu-rocketry** [comment]
This function needs an explicit `return` for the `else` case.

https://github.com/apel/ssm/blob/eb3121729a300fc41ce5ef49e5ecea3acc4206e9/ssm/ssm2.py#L375

**Comment by DanielPerkins7** [comment]
What should be returned in the else case?

**Comment by tofu-rocketry** [comment]
Just the Python default of `return None`
