### ISSUE TITLE
No timeout on AMS connections (ssmsend hangs indefinitely)

### ISSUE THREAD

**Issue by maxfischer2781** [apel/ssm#243]
We have recently noticed that ``ssmsend`` and with it an entire APEL client chain can get stuck silently if there are connection issues. This seems to be caused by missing a timeout for connections.

------

When ``ssmsend`` uses AMS it directly calls the ``publish`` method, passing in only the message and retries:

https://github.com/apel/ssm/blob/eb3121729a300fc41ce5ef49e5ecea3acc4206e9/ssm/ssm2.py#L393

This gets pushed through AMS into ``requests`` and eventually ``urllib3``. Nothing in this entire chain ever sets a ``timeout``, which means "[urllib3] will *wait indefinitely* to establish a TCP connection" (see https://github.com/urllib3/urllib3/issues/1535). 

Please set a timout or at least make it configurable.

**Comment by tofu-rocketry** [comment]
Yeah, it looks like the ARGO AMS library does allow you to pass through options to the underlying `requests`/`urllib3` library, so it "should" just be a case of passing through the right option to set a TCP timeout.

We've definitely experienced the hanging connection in the past.

**Comment by tofu-rocketry** [comment]
This is now in a release: https://github.com/apel/ssm/releases/tag/3.3.1-1
