### ISSUE TITLE
Broker persistence flag

### ISSUE THREAD

**Issue by ttomttom** [apel/ssm#25]
According to this source: http://activemq.apache.org/stomp.html in order to have messages persist over broker restarts (ActiveMQ) you have to set a "persistent:true" flag in every SEND request.

Can this flag be included in the header of messages that SSM is sending?

**Comment by tofu-rocketry** [comment]
Issue mentioned in [this GGUS ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=113454).

**Comment by tofu-rocketry** [comment]
Would need to add `'persistent': 'true'` to `_send_msg` headers dictionary.

Should check the performance impact of this on the brokers.

**Comment by tofu-rocketry** [comment]
This won't be changed now we're migrating to AMS.

**Comment by tofu-rocketry** [comment]
For archival reference. Changes to `_send_msg` was to do something like:

```python
        headers = {'destination': self._dest, 'receipt': msgid,
                   'empa-id': msgid}
                   'empa-id': msgid, 'persistent': 'true'}
```
