### ISSUE TITLE
EL9: attempt to use unversioned python

### ISSUE THREAD

**Issue by kreczko** [apel/ssm#333]
It seems that for some time now, using unversioned `__python` macro [throws an error](https://fedoraproject.org/wiki/Changes/PythonMacroError) - certainly on EL9.

The fix is to add
```
%define __python /usr/bin/python3
```
at the top of the spec file.

Given that python2 is long obsolete, it might not be worth to do a conditional

**Side note**
EL9 build also requires updating the requirements:
```
Requires:	python3-stomppy < 8.0.0, python-ldap < 3.5.0, python-setuptools, openssl
```

**Comment by tofu-rocketry** [comment]
We use a different build script these days, but I will update the parts you mention so the SPEC file is at least in step until we finally retire it.
