### ISSUE TITLE
crypto.verify returns a certificate/subject pair even if a signed message has been altered

### ISSUE THREAD

**Issue by gregcorbett** [apel/ssm#39]
Discovered during development of #38.

`crypto.verify` returns a certificate/subject pair if the signed message has been tampered with after signing and hides the fact underlying openssl verification fails.

This is because :

- `crypto.get_signer_cert()` returns the signers certificate even if the signature is invalid e.g. the message body is tampered with after signing (line [148](https://github.com/apel/ssm/blob/dev/ssm/crypto.py#L148))
- The openssl command and `p1.communicate(signed_text)` can still set `message` to the message content, even if `error` is also set (lines [156](https://github.com/apel/ssm/blob/dev/ssm/crypto.py#L156) and [159](https://github.com/apel/ssm/blob/dev/ssm/crypto.py#L159))
- `crypto.verify` then returns the message body and signer certificate subject regardless of `error` (line [182](https://github.com/apel/ssm/blob/dev/ssm/crypto.py#L182))

The openssl error is logged, but the tampered message is then treated as verified.

**Comment by tofu-rocketry** [comment]
Could you post the openssl error that you get?

**Comment by gregcorbett** [comment]
this is the error
```
Verification failure
139956997355424:error:21071065:PKCS7 routines:PKCS7_signatureVerify:digest failure:pk7_doit.c:1108:
139956997355424:error:21075069:PKCS7 routines:PKCS7_verify:signature failure:pk7_smime.c:400:


```

This code snipped illustrates the issue, provided you have a trusted cert/key pair under `/etc/grid-security/`
```
from ssm import crypto

signed_message = crypto.sign("BOO", "/etc/grid-security/hostcert.pem", "/etc/grid-security/hostkey.pem")
tampered_message = signed_message.replace("BOO", "FAR")

crypto.verify(signed_message, "/etc/grid-security/certificates", False)
crypto.verify(tampered_message, "/etc/grid-security/certificates", False)
```
