### ISSUE TITLE
SSM incompatible with stomp.py >= 4.0.0

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/ssm#7]
As reported in #3, at the moment SSM is incompatible with versions of stomp.py >= 4.0.0. This is currently not significant as all the EPEL repositories (used by Scientific Linux) have versions of stomp.py <= 3.1.6. However, it would be nice if it were compatible.

Looking briefly at the code, there may be cunning ways to manipulate the imports that make adding compatibility relatively simple.

[stomp.py changelog](https://github.com/jasonrbriggs/stomp.py/blob/master/CHANGELOG)

Changes to stomp.py since last version of 3.x series: https://github.com/jasonrbriggs/stomp.py/compare/54ddd4b36be571e71d85348a38c9c32731935ae9...master

(Annoyingly, stomp.py only started using tags from version 4.0.0!)

**Comment by tofu-rocketry** [comment]
This also means SSM doesn't work with IPv6.

**Comment by tiju** [comment]
IPv6 support was added to stomp.py in v4.1.7

**Comment by tofu-rocketry** [comment]
Now only 3.1.6 is available in EPEL 6 and 7.
