### ISSUE TITLE
python-daemon should not be listed as a requirement as it is not a hard requirement.

### ISSUE THREAD

**Issue by gregcorbett** [apel/ssm#80]
Currently, the `python-daemon` package is an optional requirement in [setup.py](https://github.com/apel/ssm/blob/dev/setup.py#L61) but a hard requirement in [apel-ssm.spec](https://github.com/apel/ssm/blob/dev/apel-ssm.spec#L24). As there's no consistent way of handling optionals across packaging systems, `python-daemon` should just be left out.

We need exception handling for the case when the package is missing and an attempt is made to use the parts of our software that need it. We should also research the best way to do this.

See #70 for the original question.

**Comment by jrha** [comment]
Well it seems like a nice idea, but it depends on how much you care :grin:, I've always found the first method to be good enough.

**Comment by gregcorbett** [comment]
There is a start (possibly a finish) here: https://github.com/gregcorbett/ssm/tree/issue-80, but it needs an almighty rebase.

**Comment by tofu-rocketry** [comment]
> There is a start (possibly a finish) here: https://github.com/gregcorbett/ssm/tree/issue-80, but it needs an almighty rebase.

If you think it's just about there, can you open a pull request and then I can do any rebasing and tidying needed. (If I open it myself, I can't grant myself permission to add more commits.)
