### ISSUE TITLE
SSM hanging if exception raised when establishing connection

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/ssm#92]
From [this GGUS ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=138195):

> If apel-ssm encounters an unhandled exception, e.g.
> ```
> 2018-11-09 17:31:32,738 - ssmsend - INFO - ========================================
> 2018-11-09 17:31:32,745 - ssmsend - INFO - Starting sending SSM version 2.2.1.
> 2018-11-09 17:31:32,745 - ssmsend - INFO - Retrieving broker details from ldap://lcg-bdii.cern.ch:2170 ...
> 2018-11-09 17:31:33,660 - ssmsend - INFO - Found 2 brokers.
> 2018-11-09 17:31:33,660 - ssmsend - INFO - No server certificate supplied. Will not encrypt messages.
> 2018-11-09 17:31:33,723 - ssm.ssm2 - INFO - Connecting using SSL...
> 2018-11-09 17:31:34,638 - stomp.py - INFO - Established connection to host mq.cro-ngi.hr, port 6162
> 2018-11-09 17:31:34,817 - ssm.ssm2 - WARNING - Error message received: java.lang.SecurityException: User name [null] or password is invalid. No user for client certificate: CN=a, OU=a, O=Grid, C=CA
> 2018-11-08 16:48:18,346 - stomp.py - ERROR - An unhandled exception was encountered in the stomp receiver loop
> Traceback (most recent call last):
> File "/usr/lib/python2.6/site-packages/stomp/connect.py", line 741, in __receiver_loop
> self.__notify(frame_type, headers, body)
> File "/usr/lib/python2.6/site-packages/stomp/connect.py", line 718, in __notify
> notify_func(headers, body)
> File "/usr/lib/python2.6/site-packages/ssm/ssm2.py", line 194, in on_error
> raise Ssm2Exception()
> Ssm2Exception
> ```
> 
> then the process remains hung indefinitely. If running in the foreground, it can not be terminated with CTRL-C. The process is permanently stuck in S state (interruptible sleep, waiting for something to complete).
> 
> Each process continues to hold open a number of file handles, for example the /var/log/apel/ssmsend.log file, as well as a network socket. The hung processes need to be manually cleaned up with 'kill'.
> 
> The log output is written to the log file, so after this point there is nothing further to be done. The process should terminate cleanly instead of hanging indefinitely, but there must be some kind of improper shutdown preventing termination of the process. If there is a condition causing ssmsend to fail (the cause of which is a separate issue), and ssmsend is being regularly invoked automatically via cron, the number of hung processes, open file handles, and used network sockets will steadily grow without limit, potentially (eventually) exhausting the system limits.

Basically it seems that:

> ssm2.py should not raise an exception in its `on_error` method, it should log and cleanup its own state and simply return.

**Comment by gregcorbett** [comment]
My working theory was that the even when the SSM is acting as a sender, a stomp receiver loop is started in another thread and that loop is what the Ssm2Exception exits, rather than the "main" thread - but I wasn't able to replicate the exact error.

**Comment by tofu-rocketry** [comment]
Sort of - it's not starting a receiver, but the stomp.py sender loop is in another thread and so the exception isn't able to influence the ssm2.py processes.

Additionally, `wait=true` is set on the connection method, which means it waits for an acknowledgement from the broker, but this never comes if the user isn't authorised and so was blocking.

See #94 for proposed fix.
